### ISSUE TITLE
重构后没看懂呀 ，文件描述有点晕，help

### ISSUE THREAD

**Issue by wuqianSHANGHAI** [chong0808/shotScreen#2]
作者是否可以理一下

**Comment by dduo518** [comment]
还没重构完。。。其实我是想重构一个网页版能用的。。。。但我错了，我应该在开个分支来弄的，不应该在主分支弄的。。。找个时间回滚下先。。。然后开分支重构

**Comment by wuqianSHANGHAI** [comment]
你好，我想请教下，第二个截图窗口出来应该是如何作为画布？是不是不能全屏截图

**Comment by dduo518** [comment]
可以啊 直接 在第二个html 引入   require('./main-process'); 这个就可以了

**Comment by wuqianSHANGHAI** [comment]
好的 我之前自己试了一下，第二个窗口全屏 mac会切换到另个一个桌面，我再试试。谢谢
